---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/sub/plan":
    post:
      summary: create subscription plan
      tags:
      - SubscriptionPlans
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: integer
    get:
      summary: list subscription plans
      tags:
      - SubscriptionPlans
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
  "/sub/plan/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show subscription plan
      tags:
      - SubscriptionPlans
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
    patch:
      summary: update subscription plan
      tags:
      - SubscriptionPlans
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: new string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: integer
    put:
      summary: update subscription plan
      tags:
      - SubscriptionPlans
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: new string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: integer
  "/sub/subscription/":
    post:
      summary: create subscription
      tags:
      - Subscriptions
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    user_id: 1
                    tuition_category: string
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                subscription_plan_id:
                  type: integer
  "/sub/subscription/{id}/cancel":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    put:
      summary: cancel subscription
      tags:
      - Subscriptions
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    message: Subscription cancelled successfully
  "/sub/subscription/{id}/renew":
    parameters:
    - name: id
      in: path
      description: Subscription ID
      required: true
      schema:
        type: string
    - name: months_to_renew
      in: query
      description: Number of months to renew
      default: 1
      schema:
        type: integer
    put:
      summary: renew subscription
      tags:
      - Subscriptions
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    message: Subscription renewed successfully for 3 months
  "/sub/subscription/{id}/events":
    parameters:
    - name: id
      in: path
      description: Subscription ID
      required: true
      schema:
        type: string
    get:
      summary: list subscription events
      tags:
      - Subscriptions
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 1
                    name: Subscription Created
                    description: New subscription created
                    subscription_id: 1
                    event_type: subscription_created
                    created_at: '2023-11-26T19:21:32.123Z'
                    updated_at: '2023-11-26T19:21:32.123Z'
  "/sub/subscription":
    get:
      summary: list subscriptions
      tags:
      - Subscriptions
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 1
                    user_id: 1
                    subscription_plan_id: integer
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
  "/sub/subscription/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show subscription
      tags:
      - Subscriptions
      description: Returns a subscription
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    user_id: 1
                    subscription_plan_id: integer
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
    patch:
      summary: update subscription
      tags:
      - Subscriptions
      parameters:
      - name: id
        in: path
        description: ID of the subscription to update
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    user_id: 1
                    subscription_plan_id: integer
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                subscription_plan_id:
                  type: integer
                payment_status:
                  type: string
                expiration_date:
                  type: date
    put:
      summary: update subscription
      tags:
      - Subscriptions
      parameters:
      - name: id
        in: path
        description: ID of the subscription to update
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    user_id: 1
                    subscription_plan_id: integer
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                subscription_plan_id:
                  type: integer
                payment_status:
                  type: string
                expiration_date:
                  type: date
    delete:
      summary: delete subscription
      parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
      tags:
      - Subscriptions
      responses:
        '204':
          description: successful
  "/sub/users":
    get:
      summary: list users
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 1
                    name: string
                    email: string
                    password: 
                    siape_code: string
                    role: string
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
                    password_digest: "$2a$12$NPfxfVgQFpgcOSsojl.Kj.koRZAtCykhdIepZdPCALBe3/X6RtlNq"
    post:
      summary: create user
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    email: string
                    password: 
                    siape_code: string
                    role: string
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
                    password_digest: "$2a$12$NPfxfVgQFpgcOSsojl.Kj.koRZAtCykhdIepZdPCALBe3/X6RtlNq"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                siape_code:
                  type: string
                role:
                  type: string
  "/sub/users/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show user
      tags:
      - Users
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    email: string
                    password: 
                    siape_code: string
                    role: string
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
                    password_digest: "$2a$12$NPfxfVgQFpgcOSsojl.Kj.koRZAtCykhdIepZdPCALBe3/X6RtlNq"
    patch:
      summary: update user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    email: string
                    password: 
                    siape_code: string
                    role: string
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
                    password_digest: "$2a$12$NPfxfVgQFpgcOSsojl.Kj.koRZAtCykhdIepZdPCALBe3/X6RtlNq"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                siape_code:
                  type: string
                role:
                  type: string
    put:
      summary: update user
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    email: string
                    password: 
                    siape_code: string
                    role: string
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
                    password_digest: "$2a$12$NPfxfVgQFpgcOSsojl.Kj.koRZAtCykhdIepZdPCALBe3/X6RtlNq"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                siape_code:
                  type: string
                role:
                  type: string
    delete:
      summary: delete user
      tags:
      - Users
      responses:
        '204':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
