---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/authenticate":
    post:
      summary: Authenticate user
      tags:
      - Authentication
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user_credentials
        in: body
        schema:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
          required:
          - username
          - password
      responses:
        '200':
          description: successful
  "/refresh_token":
    post:
      summary: Refresh access token
      tags:
      - Authentication
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: refresh_token
        in: body
        schema:
          type: object
          properties:
            refresh_token:
              type: string
          required:
          - refresh_token
      responses:
        '200':
          description: successful
  "/get_user_info":
    get:
      summary: Get user information
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
      tags:
      - Authentication
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        '200':
          description: successful
  "/sub/plan":
    post:
      summary: create subscription plan
      tags:
      - SubscriptionPlans
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: new_subscription_plan
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            price:
              type: integer
      responses:
        '201':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
    get:
      summary: list subscription plans
      tags:
      - SubscriptionPlans
      produces:
      - application/json
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
  "/sub/plan/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show subscription plan
      tags:
      - SubscriptionPlans
      produces:
      - application/json
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
    patch:
      summary: update subscription plan
      tags:
      - SubscriptionPlans
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: new_subscription_plan
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            price:
              type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: new string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
    put:
      summary: update subscription plan
      tags:
      - SubscriptionPlans
      produces:
      - application/json
      consumes:
      - application/json
      parameters:
      - name: new_subscription_plan
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            description:
              type: string
            price:
              type: integer
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    name: new string
                    description: string
                    price: 100
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
  "/sub/subscription/":
    post:
      summary: create subscription
      tags:
      - Subscriptions
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: new_subscription
        in: body
        schema:
          type: object
          properties:
            user_id:
              type: string
            subscription_plan_id:
              type: integer
      responses:
        '201':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    user_id: 1
                    tuition_category: string
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
  "/sub/subscription/{id}/cancel":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    - name: Authorization
      in: header
      type: string
      required: true
    put:
      summary: cancel subscription
      tags:
      - Subscriptions
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    message: Subscription cancelled successfully
  "/sub/subscription/{id}/renew":
    parameters:
    - name: id
      in: path
      type: string
      description: Subscription ID
      required: true
    - name: months_to_renew
      in: query
      type: integer
      description: Number of months to renew
      default: 1
    - name: Authorization
      in: header
      type: string
      required: true
    put:
      summary: renew subscription
      tags:
      - Subscriptions
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    message: Subscription renewed successfully for 3 months
  "/sub/subscription/{id}/events":
    parameters:
    - name: id
      in: path
      type: string
      description: Subscription ID
      required: true
    - name: Authorization
      in: header
      type: string
      required: true
    get:
      summary: list subscription events
      tags:
      - Subscriptions
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 1
                    name: Subscription Created
                    description: New subscription created
                    subscription_id: 1
                    event_type: subscription_created
                    created_at: '2023-11-26T19:21:32.123Z'
                    updated_at: '2023-11-26T19:21:32.123Z'
  "/sub/subscription":
    get:
      summary: list subscriptions
      tags:
      - Subscriptions
      produces:
      - application/json
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                  - id: 1
                    user_id: 1
                    subscription_plan_id: integer
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
  "/sub/subscription/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    - name: Authorization
      in: header
      type: string
      required: true
    get:
      summary: show subscription
      tags:
      - Subscriptions
      produces:
      - application/json
      description: Returns a subscription
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    user_id: 1
                    subscription_plan_id: integer
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
    patch:
      summary: update subscription
      tags:
      - Subscriptions
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
      - name: id
        in: path
        type: integer
        description: ID of the subscription to update
        required: true
      - name: new_subscription
        in: body
        schema:
          type: object
          properties:
            user_id:
              type: integer
            subscription_plan_id:
              type: integer
            payment_status:
              type: string
            expiration_date:
              type: date
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    user_id: 1
                    subscription_plan_id: integer
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
    put:
      summary: update subscription
      tags:
      - Subscriptions
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: Authorization
        in: header
        type: string
        required: true
      - name: id
        in: path
        type: integer
        description: ID of the subscription to update
        required: true
      - name: new_subscription
        in: body
        schema:
          type: object
          properties:
            user_id:
              type: integer
            subscription_plan_id:
              type: integer
            payment_status:
              type: string
            expiration_date:
              type: date
      responses:
        '200':
          description: successful
          content:
            application/json:
              examples:
                example:
                  value:
                    id: 1
                    user_id: 1
                    subscription_plan_id: integer
                    payment_status: inactive
                    expiration_date: '2023-11-05T23:13:39.989Z'
                    created_at: '2023-11-05T23:13:39.989Z'
                    updated_at: '2023-11-05T23:13:39.989Z'
    delete:
      summary: delete subscription
      parameters:
      - name: id
        in: path
        type: string
        description: id
        required: true
      - name: Authorization
        in: header
        type: string
        required: true
      tags:
      - Subscriptions
      produces:
      - application/json
      responses:
        '204':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
